# Standardized Error Codes Taxonomy
AUTH_EXPIRED = "AUTH_001"
AUTH_INVALID_CREDENTIALS = "AUTH_002"

WORKSPACE_NOT_FOUND = "WORKSPACE_001"
WORKSPACE_SUSPENDED = "WORKSPACE_002"

PROJECT_NOT_FOUND = "PROJECT_001"
PROJECT_LIFECYCLE_CONFLICT = "PROJECT_002"

OWNERSHIP_CONFLICT = "OWNERSHIP_001"
OWNERSHIP_NOT_VERIFIED = "OWNERSHIP_002"

DNA_ENGINE_DISABLED = "DNA_001"
INTEL_ENGINE_ERROR = "INTEL_001"

SYSTEM_GENERIC_ERROR = "SYSTEM_001"
CONCURRENCY_ERROR = "SYSTEM_002"
