import pytest
from datetime import datetime
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from database import Base, get_db, User, Project, Workspace, WorkspaceMember, DecisionPolicy, DecisionSnapshot, ExecutiveRecommendation
from main import app
from auth.security import get_current_user

# Setup test database
TEST_DATABASE_URL = "sqlite:///test_decision_governance.db"
engine = create_engine(TEST_DATABASE_URL, connect_args={"check_same_thread": False})
TestingSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

@pytest.fixture(scope="module", autouse=True)
def setup_test_db():
    Base.metadata.create_all(bind=engine)
    yield
    Base.metadata.drop_all(bind=engine)

@pytest.fixture
def db_session():
    db = TestingSessionLocal()
    try:
        # Seed Workspace
        ws = db.query(Workspace).filter(Workspace.workspace_id == "test-ws-gov").first()
        if not ws:
            ws = Workspace(
                workspace_id="test-ws-gov",
                name="Test Workspace Governance",
                created_at=datetime.utcnow()
            )
            db.add(ws)
            db.commit()

        # Seed User
        user = db.query(User).filter(User.uuid == "test-user-gov").first()
        if not user:
            user = User(
                uuid="test-user-gov",
                email="cto@yowon.ai",
                password_hash="mock",
                full_name="CTO Reviewer",
                role="WORKSPACE_ADMIN",
                status="ACTIVE"
            )
            db.add(user)
            db.commit()

        # Seed WorkspaceMember
        member = db.query(WorkspaceMember).filter(
            WorkspaceMember.user_id == "test-user-gov",
            WorkspaceMember.workspace_id == "test-ws-gov"
        ).first()
        if not member:
            member = WorkspaceMember(
                workspace_id="test-ws-gov",
                user_id="test-user-gov",
                role="WORKSPACE_ADMIN",
                status="ACCEPTED"
            )
            db.add(member)
            db.commit()

        yield db
    finally:
        db.close()

@pytest.fixture
def client(db_session):
    def override_get_db():
        try:
            yield db_session
        finally:
            pass
            
    def override_current_user():
        return db_session.query(User).filter(User.uuid == "test-user-gov").first()
        
    app.dependency_overrides[get_db] = override_get_db
    app.dependency_overrides[get_current_user] = override_current_user
    yield TestClient(app)
    app.dependency_overrides.clear()


# ── Tests ─────────────────────────────────────────────────────────────────────

def test_decision_generation_and_scoring(client, db_session):
    # Seed Project
    proj = Project(id="test-proj-dec", name="Decision Test Project", workspace_id="test-ws-gov")
    db_session.add(proj)
    db_session.commit()

    # Get decision
    res = client.get("/api/v1/decision/projects/test-proj-dec")
    assert res.status_code == 200
    data = res.json()["data"]
    assert data["project_id"] == "test-proj-dec"
    assert data["overall_score"] > 0.0
    assert data["verdict"] in ["APPROVED", "REVIEW_REQUIRED", "REJECTED"]


def test_recommendation_ownership_lifecycle(client, db_session):
    # Retrieve recommendations generated by the previous test
    res = client.get("/api/v1/decision/recommendations?project_id=test-proj-dec")
    assert res.status_code == 200
    recs = res.json()["data"]
    assert len(recs) > 0
    rec_uuid = recs[0]["uuid"]

    # Assign recommendation
    res_assign = client.post(f"/api/v1/decision/{rec_uuid}/assign?owner=DeveloperA")
    assert res_assign.status_code == 200
    assert res_assign.json()["data"]["status"] == "Assigned"
    assert res_assign.json()["data"]["suggested_owner"] == "DeveloperA"

    # Close recommendation
    res_close = client.post(f"/api/v1/decision/{rec_uuid}/verify")
    assert res_close.status_code == 200
    assert res_close.json()["data"]["status"] == "Closed"


def test_what_if_simulation_endpoints(client, db_session):
    payload = {"security_score_adjustment": 10.0, "engineering_score_adjustment": 5.0}
    res = client.post("/api/v1/decision/projects/test-proj-dec/simulate", json=payload)
    assert res.status_code == 200
    data = res.json()["data"]
    assert data["project_id"] == "test-proj-dec"
    assert data["predicted_score"] > 0.0


def test_ask_yowon_assistant_endpoint(client, db_session):
    payload = {"query": "Explain the decision status", "project_id": "test-proj-dec"}
    res = client.post("/api/v1/decision/assistant/query", json=payload)
    assert res.status_code == 200
    data = res.json()["data"]
    assert "response" in data
    assert len(data["referenced_evidence_ids"]) > 0


def test_governance_workflow_and_reviews(client, db_session):
    # Get workflow status
    res = client.get("/api/v1/governance/projects/test-proj-dec")
    assert res.status_code == 200
    steps = res.json()["data"]
    assert len(steps) > 0
    step_name = steps[0]["step_name"]

    # Submit review
    payload = {"status": "APPROVED", "reviewer_comments": "Verified compliant with policy version 1."}
    res_rev = client.post(f"/api/v1/governance/review?project_id=test-proj-dec&step_name={step_name}", json=payload)
    assert res_rev.status_code == 200
    assert res_rev.json()["data"]["status"] == "APPROVED"
    assert res_rev.json()["data"]["compliance_status"] == "COMPLIANT"


def test_executive_reports_endpoints(client, db_session):
    res_exec = client.get("/api/v1/decision/reports/executive?project_id=test-proj-dec")
    assert res_exec.status_code == 200
    assert res_exec.json()["data"]["report_title"] == "Executive Software Quality Assessment"

    res_sec = client.get("/api/v1/decision/reports/security?project_id=test-proj-dec")
    assert res_sec.status_code == 200
    assert res_sec.json()["data"]["report_title"] == "Executive Security Assessment"


def test_portfolio_benchmarks_and_trends(client, db_session):
    # Trends
    res_trends = client.get("/api/v1/decision/portfolio/trends", headers={"x-workspace-id": "test-ws-gov"})
    assert res_trends.status_code == 200
    assert len(res_trends.json()["data"]) > 0

    # Benchmarks
    res_bench = client.get("/api/v1/decision/portfolio/benchmarks", headers={"x-workspace-id": "test-ws-gov"})
    assert res_bench.status_code == 200
    assert "workspace_average" in res_bench.json()["data"]
