# List of contract event types
PROJECT_CREATED = "PROJECT_CREATED"
PROJECT_UPDATED = "PROJECT_UPDATED"
PROJECT_ARCHIVED = "PROJECT_ARCHIVED"

TEAM_CREATED = "TEAM_CREATED"
TEAM_MEMBER_JOINED = "TEAM_MEMBER_JOINED"

REPOSITORY_SYNC_STARTED = "REPOSITORY_SYNC_STARTED"
REPOSITORY_SYNC_COMPLETED = "REPOSITORY_SYNC_COMPLETED"

EVALUATION_STARTED = "EVALUATION_STARTED"
EVALUATION_COMPLETED = "EVALUATION_COMPLETED"

OWNERSHIP_TRANSFERRED = "OWNERSHIP_TRANSFERRED"
COMMENT_CREATED = "COMMENT_CREATED"
ATTACHMENT_UPLOADED = "ATTACHMENT_UPLOADED"
NOTIFICATION_CREATED = "NOTIFICATION_CREATED"
