# Enterprise Settings configuration limits for Phase 8A

CONNECTOR_RATE_LIMIT = 5000  # Requests per hour
PLUGIN_MAX_MEMORY_MB = 512.0
PLUGIN_MAX_CPU_PERCENT = 80.0
WEBHOOK_MAX_RETRIES = 5
SECRET_ROTATION_DAYS = 90
SYNC_TIMEOUT_SECONDS = 3600
