from enum import Enum

class LifecycleState(str, Enum):
    DRAFT = "DRAFT"
    REGISTERED = "REGISTERED"
    DEVELOPMENT = "DEVELOPMENT"
    EVALUATION_RUNNING = "EVALUATION_RUNNING"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    PRODUCTION = "PRODUCTION"
    ARCHIVED = "ARCHIVED"

class NotificationCategory(str, Enum):
    REPOSITORY = "REPOSITORY"
    EVALUATION = "EVALUATION"
    OWNERSHIP = "OWNERSHIP"
    WORKSPACE = "WORKSPACE"
    SECURITY = "SECURITY"
    VERSION = "VERSION"
    DISCUSSION = "DISCUSSION"
    INVITATION = "INVITATION"
    SYSTEM = "SYSTEM"

class JobType(str, Enum):
    REPO_SYNC = "REPO_SYNC"
    METADATA_EXTRACT = "METADATA_EXTRACT"
    FILE_INDEX = "FILE_INDEX"
    NOTIF_DISPATCH = "NOTIF_DISPATCH"
    DNA_GEN = "DNA_GEN"
    INTEL_REFRESH = "INTEL_REFRESH"

class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
