"""add_analysis_lifecycle_columns

Revision ID: 1c6fa2941993
Revises: 4e457597937b
Create Date: 2026-07-04 15:02:15.364919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6fa2941993'
down_revision: Union[str, Sequence[str], None] = '4e457597937b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_evaluations_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_evaluations_evaluation_id'), ['evaluation_id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_workspace_id'), ['workspace_id'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_evaluation_id'), ['evaluation_id'], unique=False)

    with op.batch_alter_table('repository_analyses', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('current_stage',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('current_module',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('repository_snapshots', schema=None) as batch_op:
        batch_op.alter_column('previous_snapshot_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_snapshot_previous_snapshot', 'repository_snapshots', ['previous_snapshot_id'], ['snapshot_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint('fk_snapshot_previous_snapshot', type_='foreignkey')
        batch_op.alter_column('previous_snapshot_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('repository_analyses', schema=None) as batch_op:
        batch_op.alter_column('current_module',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('current_stage',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_evaluation_id'))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_workspace_id'))

    with op.batch_alter_table('agent_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_evaluations_evaluation_id'))
        batch_op.drop_index(batch_op.f('ix_agent_evaluations_agent_name'))

    # ### end Alembic commands ###
